driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5455/electromachine_test
username=postgres
password=postgres
contexts=production,test
promptOnNonLocalDatabase=false
verbose=false
outputFileEncoding=UTF-8
includeArtifact=false