server:
  port: 8090
  servlet:
    context-path: /electromachine
    session:
      cookie:
        name: ELECTROMACHINE_SESSION
spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/electromachine
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5450/electromachine
    user: postgres
    password: postgres
    contexts: production

  security:
    oauth2:
      client:
        registration:
          keycloak: # произвольное название. Проставляем название сервера авторизации
            client-id: electromachine-client
            client-secret: emRSEHRq4FEl24ObYYr7sfboYuu6bvKU
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/electromachine
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/electromachine
          jwk-set-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/certs

  session:
    timeout: 10m
    redis:
      namespace: electromachine

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

electromachine:
  ip:
    address: http://localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG