server:
  port: 8090
  servlet:
    context-path: /electromachine

spring:
  application:
    name: electromachine
  datasource:
    url: jdbc:postgresql://localhost:5450/electromachine
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5450/electromachine
    user: postgres
    password: postgres
    contexts: production

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: electromachine-client
            client-secret: emRSEHRq4FEl24ObYYr7sfboYuu6bvKU
            scope: openid,roles
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/electromachine
            authorization-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/electromachine
          jwk-set-uri: http://keycloak:8080/realms/electromachine/protocol/openid-connect/certs

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

electromachine:
  ip:
    address: http://localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      vaadin: DEBUG