version: "3.8"
services:
  electromachine:
    image: "electromachine"
    container_name: "electromachine"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5450/electromachine
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5450/electromachine
      - DISCOVERY_SERVICE_URL=http://electromachine-discovery:8761/eureka/

  electromachine-gateway:
    image: "electromachine-gateway"
    container_name: "electromachine-gateway"
    ports:
      - "9090:9090"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - DISCOVERY_SERVICE_URL=http://electromachine-discovery:8761/eureka/
      - ELECTROMACHINE_URL=http://electromachine

  electromachine-discovery:
    image: "electromachine-discovery"
    container_name: "electromachine-discovery"
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=electromachine-discovery

  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5450:5450"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=electromachine
      - PGPORT=5450
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d electromachine"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:16.1
    container_name: postgres-test
    ports:
      - "5455:5455"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=electromachine_test
      - PGPORT=5455
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d electromachine-test"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: "keycloak"
    command: start-dev --import-realm # start keycloak in development mode
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME=keycloak
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 5s
      timeout: 5s
      retries: 100

  redis:
    image: "redis:7.2.4"
    container_name: "redis"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  postgres_test_data: