# Используем официальный образ Keycloak 26.0
FROM quay.io/keycloak/keycloak:26.0

# Устанавливаем рабочую директорию
WORKDIR /opt/keycloak

# Копируем провайдер magic link
COPY keycloak-providers/keycloak-magic-link.jar /opt/keycloak/providers/

# Копируем кастомные темы
# COPY keycloak-themes/ /opt/keycloak/themes/

# Собираем Keycloak с провайдером
RUN /opt/keycloak/bin/kc.sh build --features=preview

# Экспонируем порты
EXPOSE 8080
EXPOSE 8443

# Команда запуска
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]