parent=base
styles=css/styles.css
encoding=UTF-8
locales=ru,en
defaultLocale=ru
messages=messages_ru.properties
loginWidth=450px

# Важно! Укажите ВСЕ переопределяемые шаблоны
templateOverrides=
    login=templates/login.ftl,
    login-selector=templates/login-selector.ftl,
    login-username=templates/login-username.ftl,
    login-password=templates/login-password.ftl,
    login-magic-link=templates/login-magic-link.ftl,
    login-config-totp=templates/login-config-totp.ftl,
    login-update-profile=templates/login-update-profile.ftl,
    login-verify-email=templates/login-verify-email.ftl,
    login-page-expired=templates/login-page-expired.ftl,
    login-oauth-grant=templates/login-oauth-grant.ftl